# Node.js Application
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rocketstarter-app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      SQLITE_PATH: ./data/database.sqlite
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./data:/app/data
      - /app/node_modules
    networks:
      - rocketstarter-network
    command: npm run dev:watch

networks:
  rocketstarter-network:
    driver: bridge